# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20170807_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('origen', models.CharField(choices=[('Ciudad1', 'Ciudad1'), ('Ciudad2', 'Ciudad2'), ('Ciudad3', 'Ciudad3'), ('Ciudad4', 'Ciudad4'), ('Ciudad5', 'Ciudad5')], default='Ciudad1', max_length=11)),
                ('destino', models.CharField(choices=[('Ciudad1', 'Ciudad1'), ('Ciudad2', 'Ciudad2'), ('Ciudad3', 'Ciudad3'), ('Ciudad4', 'Ciudad4'), ('Ciudad5', 'Ciudad5')], default='Ciudad2', max_length=11)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adquiriente', models.CharField(max_length=10)),
                ('puesto', models.IntegerField()),
            ],
        ),
    ]
